CityCenter/CityCenter.WebUI.Frontend/Models/Panel/AdminExcursionReservationDetailsModel.cs
using PagedList;

namespace CityCenter.WebUI.Frontend.Models.Panel
{
    public class AdminExcursionReservationDetailsModel
    {
        public StaticPagedList<ExcursionReservationDetailsModel> ReservationDetails { get; set; }

        public int ExcursionId { get; set; }
    }
}

CityCenter/CityCenter.WebUI.Frontend/Models/Panel/AdminHotelReservationDetailsModel.cs
using CityCenter.Entities;
using PagedList;

namespace CityCenter.WebUI.Frontend.Models.Panel
{
    public class AdminHotelReservationDetailsModel
    {
        public StaticPagedList<HotelReservationDetails> ReservationDetails { get; set; }

        public int HotelId { get; set; }
    }
}

CityCenter/CityCenter.WebUI.Frontend/Models/Panel/ExcursionAdministratorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CityCenter.Entities;

namespace CityCenter.WebUI.Frontend.Models.Panel
{
    public class ExcursionAdministratorModel
    {
        public List<Role> UserRoles { get; set; }

        public IList<SelectListItem> CurrentExcursion { get; set; }

        [DisplayName("Excursion")]
        [Required]
        public int SelectedExcursionId { get; set; }
    }
}

CityCenter/CityCenter.WebUI.Frontend/Models/Panel/ExcursionReservationDetailsModel.cs
using CityCenter.Entities;

namespace CityCenter.WebUI.Frontend.Models.Panel
{
    public class ExcursionReservationDetailsModel
    {
        public ExcursionReservationDetails ReservationDetails { get; set; }

        public User User { get; set; }
    }
}

CityCenter/CityCenter.WebUI.Frontend/Models/Panel/HotelAdministratorPanelModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using CityCenter.Entities;

namespace CityCenter.WebUI.Frontend.Models.Panel
{
    public class HotelAdministratorPanelModel
    {
        public List<Role> UserRoles { get; set; }

        public IList<SelectListItem> CurrentHotels { get; set; }

        [DisplayName("Hotel")]
        [Required]
        public int SelectedHotelId { get; set; }
    }
}

CityCenter/CityCenter.WebUI.Frontend/Models/Panel/HotelReservationDetailsModel.cs
using CityCenter.Entities;

namespace CityCenter.WebUI.Frontend.Models.Panel
{
    public class HotelReservationDetailsModel
    {
        public HotelReservationDetails ReservationDetails { get; set; }
    }
}

CityCenter/CityCenter.WebUI.Frontend/Models/Panel/PanelUserInfoModel.cs
using System.ComponentModel.DataAnnotations;

namespace CityCenter.WebUI.Frontend.Models.Panel
{
    public class PanelUserInfoModel
    {
        [Required(ErrorMessage = "Name is required")]
        [StringLength(30, ErrorMessage = "Length should not exceed 30")]
        [RegularExpression(@"^[a-zA-Zа-яА-ЯіІ]{1,30}", ErrorMessage = "Invalid first name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Surname is required")]
        [StringLength(30, ErrorMessage = "Length should not exceed 30")]
        [RegularExpression(@"^[a-zA-Zа-яА-ЯіІ]{1,30}", ErrorMessage = "Invalid surname")]
        public string Surname { get; set; }

        [Required(ErrorMessage = "Phone is required")]
        [StringLength(13, ErrorMessage = "Length should be 13")]
        [RegularExpression(@"^\+[1-9]{1}[0-9]{11}$", ErrorMessage = "Invalid Phone")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Email is required")]
        [StringLength(50, ErrorMessage = "Length should not exceed 50")]
        [RegularExpression(@"^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$", ErrorMessage = "Invalid email")]
        public string Email { get; set; }
    }
}

CityCenter/CityCenter.WebUI.Frontend/Controllers/EapNavigationController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using CityCenter.BLL.Abstract;
using CityCenter.WebUI.Abstract;
using CityCenter.WebUI.Frontend.Models.Panel;

namespace CityCenter.WebUI.Frontend.Controllers
{
    public class EapNavigationController : Controller
    {
        #region Fields

        private readonly IUsersManager _userManager;
        private readonly IExcursionsManager _excursionsManager;
        private readonly ISecurityManager _securityManager;

        #endregion

        #region Constructor

        public EapNavigationController(IUsersManager usersManager, IExcursionsManager excursionsManager, ISecurityManager securityManager)
        {
            _userManager = usersManager;
            _excursionsManager = excursionsManager;
            _securityManager = securityManager;
        }

        #endregion

        #region WebActions

        [HttpGet]
        [ChildActionOnly]
        public ActionResult Menu()
        {
            var userId = _securityManager.GetCurrentUserId();
            var model = new ExcursionAdministratorModel()
            {
                UserRoles = _userManager.GetUserRoles(userId),
                CurrentExcursion = ConvertToSelectListItem(),
            };

            return PartialView("_ExcursionMenu", model);
        }

        #endregion

        #region Helper

        private List<SelectListItem> ConvertToSelectListItem()
        {
            var userId = _securityManager.GetCurrentUserId();
            var excursion = _excursionsManager.GetExcursionsByAdminId(userId);
            return excursion.Select(e => new SelectListItem() { Text = e.Name, Value = e.Id.ToString() }).ToList();
        }

        #endregion
    }
}

CityCenter/CityCenter.WebUI.Frontend/Controllers/ExcursionAdministratorPanelController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CityCenter.BLL.Abstract;
using CityCenter.WebUI.Abstract;
using CityCenter.WebUI.Frontend.Code;
using CityCenter.WebUI.Frontend.Models.Excursion;
using CityCenter.WebUI.Frontend.Models.Helper;
using CityCenter.WebUI.Frontend.Models.Panel;
using PagedList;

namespace CityCenter.WebUI.Frontend.Controllers
{
    [AuthorizeOrThrow404("ExcursionAdmin")]
    public class ExcursionAdministratorPanelController : Controller
    {
        #region Fields

        private readonly IExcursionsManager _excursionsManager;

        private readonly ISecurityManager _securityManager;

        private readonly IUsersManager _usersManager;

        private readonly IEmailManager _emailManager;

        #endregion

        #region Constructor

        public ExcursionAdministratorPanelController(IExcursionsManager excursionsManager, ISecurityManager securityManager, IUsersManager usersManager, IEmailManager emailManager)
        {
            _excursionsManager = excursionsManager;
            _securityManager = securityManager;
            _usersManager = usersManager;
            _emailManager = emailManager;
        }

        #endregion

        #region WebActions

        [HttpGet]
        public ActionResult Panel()
        {
            return View();
        }

        [HttpGet]
        public ActionResult EditExcursionContent(int excursionId)
        {
            #region Validation

            var userId = _securityManager.GetCurrentUserId();

            if (!_securityManager.IsUserAdministratorOfExcursion(userId, excursionId))
            {
                throw new HttpException(404, "HTTP/1.1 404 Not Found");
            }

            #endregion

            var excursionDiscriptionModel = new ExcursionDescriptionModel()
            {
                Description = _excursionsManager.GetExcursionDescriptionById(excursionId),
                Excursion = _excursionsManager.GetExcursionById(excursionId),
                Name = _excursionsManager.GetExcursionById(excursionId).Name
            };

            var totalSize = _excursionsManager.GetPendingReservationsCountByExcursionId(excursionId);
            ViewBag.CountOfPendingReservation = totalSize;
            return PartialView("_EditExcursionContent", excursionDiscriptionModel);
        }

        [HttpPost]
        public ActionResult EditExcursionContent(ExcursionDescriptionModel model)
        {
            if (ModelState.IsValid)
            {
                _excursionsManager.UpdateExcursionDescription(model.Description);
                _excursionsManager.UpdateExcursionName(model.Excursion.Name, model.Description.ExcursionId);
                return RedirectToAction("Panel");
            }
            return PartialView("_EditExcursionContent");
        }

        [HttpPost]
        public ActionResult UploadNewImage(int excursionId, HttpPostedFileBase image)
        {
            if (image != null)
            {
                var excursionDescription = _excursionsManager.GetExcursionDescriptionById(excursionId);
                excursionDescription.Photo = new byte[image.ContentLength];
                excursionDescription.PhotoExtension = image.ContentType;
                image.InputStream.Read(excursionDescription.Photo, 0, image.ContentLength);
                _excursionsManager.UpdateExcursionImage(excursionDescription);
            }
            return RedirectToAction("EditExcursionContent", new { excursionId });
        }

        [HttpGet]
        public ActionResult PendingReservations(int excursionId, int page = 1)
        {
            #region Validation

            var userId = _securityManager.GetCurrentUserId();

            if (!_securityManager.IsUserAdministratorOfExcursion(userId, excursionId))
            {
                throw new HttpException(404, "HTTP/1.1 404 Not Found");
            }

            #endregion

            var pagedListModel = new PagedListModel()
            {
                Page = page,
                PageSize = 2,
                TotalItems = _excursionsManager.GetPendingReservationsCountByExcursionId(excursionId)
            };

            ViewBag.TotalItems = pagedListModel.TotalItems;
            ViewBag.PageSize = pagedListModel.PageSize;

            #region Paging Validation

            if (page < 1)
            {
                return RedirectToAction("PendingReservations");
            }
            if (page != 1 && (page - 1) * pagedListModel.PageSize >= pagedListModel.TotalItems)
            {
                return RedirectToAction("PendingReservations", new
                {
                    page = Math.Ceiling((double)pagedListModel.TotalItems / pagedListModel.PageSize)
                });
            }

            #endregion

            var reservationEntities = _excursionsManager.GetPendingReservationsByExcursionId(excursionId, pagedListModel.Page,
                pagedListModel.PageSize);
            var reservations = reservationEntities.Select(item => new ExcursionReservationDetailsModel()
            {
                ReservationDetails = item,
                User = _usersManager.GetUserById(item.UserId)
            }).ToList();
            var pagedList = new StaticPagedList<ExcursionReservationDetailsModel>(reservations, page, pagedListModel.PageSize,
                pagedListModel.TotalItems);
            var model = new AdminExcursionReservationDetailsModel()
            {
                ReservationDetails = pagedList,
                ExcursionId = excursionId
            };
            ViewBag.CountOfPendingReservation = _excursionsManager.GetPendingReservationsCountByExcursionId(excursionId);

            return View(model);

        }

        [HttpGet]
        public ActionResult AcceptedReservations(int excursionId, int page = 1)
        {
            #region Validation

            var userId = _securityManager.GetCurrentUserId();

            if (!_securityManager.IsUserAdministratorOfExcursion(userId, excursionId))
            {
                throw new HttpException(404, "HTTP/1.1 404 Not Found");
            }

            #endregion

            var pagedListModel = new PagedListModel()
            {
                Page = page,
                PageSize = 3,
                TotalItems = _excursionsManager.GetAcceptedReservationsCountByExcursionId(excursionId)
            };

            ViewBag.TotalItems = pagedListModel.TotalItems;
            ViewBag.PageSize = pagedListModel.PageSize;

            #region Paging Validation

            if (page < 1)
            {
                return RedirectToAction("AcceptedReservations");
            }
            if (page != 1 && (page - 1) * pagedListModel.PageSize >= pagedListModel.TotalItems)
            {
                return RedirectToAction("AcceptedReservations", new { page = Math.Ceiling((double)pagedListModel.TotalItems / pagedListModel.PageSize) });
            }

            #endregion

            var reservationEntities = _excursionsManager.GetAcceptedReservationsByExcursionId(excursionId, pagedListModel.Page,
               pagedListModel.PageSize);
            var reservations = reservationEntities.Select(item => new ExcursionReservationDetailsModel()
            {
                ReservationDetails = item,
                User = _usersManager.GetUserById(item.UserId)
            }).ToList();
            var pagedList = new StaticPagedList<ExcursionReservationDetailsModel>(reservations, page, pagedListModel.PageSize,
                  pagedListModel.TotalItems);
            var model = new AdminExcursionReservationDetailsModel()
            {
                ReservationDetails = pagedList,
                ExcursionId = excursionId
            };
            ViewBag.CountOfPendingReservation = _excursionsManager.GetPendingReservationsCountByExcursionId(excursionId);

            return View(model);
        }

        [HttpPost]
        public ActionResult AcceptReservation(int reservationId, int excursionId)
        {
            var hotelName = _excursionsManager.GetExcursionById(excursionId).Name;
            _excursionsManager.AcceptReservation(reservationId);
            SendEmailReservationNotification(hotelName, reservationId, reservationStatus: "Accepted");
            return RedirectToAction("PendingReservations", new { excursionId });
        }

        [HttpPost]
        public ActionResult DeclineReservation(int reservationId, int excursionId)
        {
            var hotelName = _excursionsManager.GetExcursionById(excursionId).Name;
            _excursionsManager.DeclineReservation(reservationId);
            SendEmailReservationNotification(hotelName, reservationId, reservationStatus: "Declined");
            return RedirectToAction("PendingReservations", new { excursionId });
        }

        #endregion

        #region Helper

        public FileContentResult GetHotelImage(int excursionId)
        {
            var desc = _excursionsManager.GetExcursionDescriptionById(excursionId);
            return File(desc.Photo, MimeMapping.GetMimeMapping(desc.PhotoExtension));
        }

        private void SendEmailReservationNotification(string excursionName, int reservationId, string reservationStatus)
        {
            var userId = _usersManager.GetUserIdByReservationId(reservationId);
            var user = _usersManager.GetUserById(userId);

            var mailSubject = "Reservation Notification";
            var mailBody = string.Format(
                "<div style=\"font-size:16px;\">Dear {0} {1}.<br/>"
                + "Your Registration to excursion {2} was : {3}",
                user.FirstName, user.Surname, excursionName, reservationStatus);

            _emailManager.SendEmail(user.Email, mailSubject, mailBody);
        }

        #endregion
    }
}

CityCenter/CityCenter.WebUI.Frontend/Views/ExcursionAdministratorPanel/AcceptedReservations.cshtml
@using System.Web.Optimization
@using PagedList.Mvc
@model CityCenter.WebUI.Frontend.Models.Panel.AdminExcursionReservationDetailsModel
@{
    ViewBag.Title = "Accepted Reservations";
    Layout = "~/Views/ExcursionAdministratorPanel/_MenuLayout.cshtml";
    var totalItems = ViewBag.TotalItems;
    var pageSize = ViewBag.PageSize;
}

@section style{
    @Styles.Render("~/Content/show-reservations")
    @Styles.Render("~/Content/paged-list")
}

<div id="wrapper-panel-body">
    <div id="wrapper-panel-body-func">
        @Html.Partial("_Navigation", new ViewDataDictionary { { "id", @Model.ExcursionId }, { "PendingCount", ViewBag.CountOfPendingReservation } })
        <div id="wrapper-panel-func">
            @if (@Model.ReservationDetails.Count != 0)
            {
                foreach (var reservation in @Model.ReservationDetails)
                {
                    @Html.Partial("_Reservations", reservation)
                }
                if (totalItems > pageSize)
                {
                    @Html.PagedListPager(Model.ReservationDetails, page => @Url.Action("AcceptReservation", "ExcursionAdministratorPanel", new { excursionId = @Model.ExcursionId, page }))
                }
            }
            else
            {
                <h3>No reservations</h3>
            }
        </div>
    </div>
</div>

CityCenter/CityCenter.WebUI.Frontend/Views/ExcursionAdministratorPanel/Panel.cshtml
@model CityCenter.WebUI.Frontend.Models.Panel.ExcursionAdministratorModel

@{
    ViewBag.Title = "Panel";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}
<div id="wrapper-menu">
    @{ Html.RenderAction("Menu", "EapNavigation");}
</div>

CityCenter/CityCenter.WebUI.Frontend/Views/ExcursionAdministratorPanel/PendingReservations.cshtml
@using System.Web.Optimization
@using PagedList.Mvc
@model CityCenter.WebUI.Frontend.Models.Panel.AdminExcursionReservationDetailsModel
@{
    ViewBag.Title = "Pending Reservations";
    Layout = "~/Views/ExcursionAdministratorPanel/_MenuLayout.cshtml";
    var totalItems = ViewBag.TotalItems;
    var pageSize = ViewBag.PageSize;
}

@section style{
    @Styles.Render("~/Content/show-reservations")
    @Styles.Render("~/Content/paged-list")
}

<div id="wrapper-panel-body">
    <div id="wrapper-panel-body-func">
        @Html.Partial("_Navigation", new ViewDataDictionary { { "id", @Model.ExcursionId }, { "PendingCount", ViewBag.CountOfPendingReservation } })
        <div id="wrapper-panel-func">
            @if (@Model.ReservationDetails.Count != 0)
            {
                foreach (var reservation in @Model.ReservationDetails)
                {
                    @Html.Partial("_Reservations", reservation)
                }
                if (totalItems > pageSize)
                {
                    @Html.PagedListPager(Model.ReservationDetails, page => @Url.Action("PendingReservations", "ExcursionAdministratorPanel", new { excursionId = @Model.ExcursionId, page }))
                }
            }
            else
            {
                <h3>No reservations</h3>
            }
        </div>
    </div>
</div>

CityCenter/CityCenter.WebUI.Frontend/Views/ExcursionAdministratorPanel/_EditExcursionContent.cshtml
@using System.Web.Optimization
@model CityCenter.WebUI.Frontend.Models.Excursion.ExcursionDescriptionModel
@{
    ViewBag.Title = "EditExcursionContent";
    Layout = "~/Views/ExcursionAdministratorPanel/_MenuLayout.cshtml";
}

@section style{

    @Styles.Render("~/Content/edit-content")
}

<div id="wrapper-panel-body">
    <div id="wrapper-panel-body-func">
        @Html.Partial("_Navigation", new ViewDataDictionary { { "id", @Model.Description.ExcursionId }, { "PendingCount", ViewBag.CountOfPendingReservation } })
        <div id="wrapper-panel-func">
            @using (Html.BeginForm("EditExcursionContent", "ExcursionAdministratorPanel", FormMethod.Post, new { @id = "request-form" }))
            {
                <div id="wrapper-txt-box">
                    <div class="txt-box">
                        @Html.LabelFor(m => m.Excursion.Name)
                        @Html.TextBoxFor(m => m.Excursion.Name)
                    </div>
                    <div class="txt-box">
                        @Html.LabelFor(m => m.Excursion.Address)
                        @Html.TextBoxFor(m => m.Excursion.Address)
                    </div>
                    <div class="txt-box">
                        @Html.LabelFor(m => m.Excursion.BeginTime)
                        @Html.TextBoxFor(m => m.Excursion.BeginTime)
                    </div>
                    <div class="txt-box">
                        @Html.LabelFor(m => m.Excursion.Duration)
                        @Html.TextBoxFor(m => m.Excursion.Duration)
                    </div>
                </div>
                <div id="txt-area-head-ex">
                    @Html.LabelFor(m => m.Description.ShortDescription)
                    @Html.TextAreaFor(m => m.Description.ShortDescription)
                </div>
                <div id="txt-area-desc-ex">
                    @Html.LabelFor(m => m.Description.LongDescription)
                    @Html.TextAreaFor(m => m.Description.LongDescription)
                </div>
                @Html.HiddenFor(m => m.Description.ExcursionId)
                <input type="submit" id="edit-button" name="edit-button" value="Edit" />
            }
            @using (Html.BeginForm("UploadNewImage", "ExcursionAdministratorPanel", new { excursionId = @Model.Description.ExcursionId }, FormMethod.Post, new { enctype = "multipart/form-data", @id = "choise-img" }))
            {
                <img src="@Url.Action("GetExcursionImage", "Excursions", new { @Model.Description.ExcursionId })" alt="@Model.Excursion.Name" />
                <input type="file" name="Image" />
                <input type="submit" value="Update Photo" />
            }
        </div>
    </div>
</div>

CityCenter/CityCenter.WebUI.Frontend/Views/ExcursionAdministratorPanel/_MenuLayout.cshtml
@{
    ViewBag.Title = "Panel";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}
@section scripts{
    @RenderSection("scripts", false)
}
@section style{
    @RenderSection("style", false)

}

<div id="wrapper-menu">
    @{
        Html.RenderAction("Menu", "EapNavigation");
    }

</div>
@RenderBody()

CityCenter/CityCenter.WebUI.Frontend/Views/ExcursionAdministratorPanel/_Navigation.cshtml
@using CityCenter.WebUI.Frontend.Code
@{
    var excursionId = (int)ViewData["id"];
    var countOfPendingReservation = (int)ViewData["PendingCount"];
}
<div id="wrapper-panel-button">
    <a href="@Url.Action("EditExcursionContent", "ExcursionAdministratorPanel", new {excursionId})">
        <div class="panel-buttons @Html.ActivePage("EditExcursionContent", "ExcursionAdministratorPanel")">
            Edit Excursion Content
        </div>
    </a>
    <a href="@Url.Action("AcceptedReservations", "ExcursionAdministratorPanel", new {excursionId })">
        <div class="panel-buttons @Html.ActivePage("AcceptedReservations", "ExcursionAdministratorPanel")">
            Reservations
        </div>
    </a>

    <a href="@Url.Action("PendingReservations", "ExcursionAdministratorPanel", new {excursionId })">
        <div class="panel-buttons @Html.ActivePage("PendingReservations", "ExcursionAdministratorPanel")">
            Pending Reservations @if (countOfPendingReservation != 0)
            {
                <span id="count-reservation">+@countOfPendingReservation</span>
            }
        </div>
    </a>
</div>

CityCenter/CityCenter.WebUI.Frontend/Views/ExcursionAdministratorPanel/_Reservations.cshtml
@model CityCenter.WebUI.Frontend.Models.Panel.ExcursionReservationDetailsModel

@{
    string status;
    var activeStatus = "";
}
<div id="@(Model.ReservationDetails.Status == 0 ? "wrapper-reservations-body-with-button" : "wrapper-reservations-body")">
    <div id="reservation-header">
        @switch (Model.ReservationDetails.Status)
        {
            case 0:
                status = "Pending";
                break;
            case 1:
                status = "Declined";
                break;
            case 2:
                status = "Accepted";
                break;
            default:
                status = "";
                break;
        }
        @switch (status)
        {
            case "Pending":
                activeStatus = "pending";
                break;
            case "Declined":
                activeStatus = "decline";
                break;
            case "Accepted":
                activeStatus = "in-progress";
                break;
        }
        <div class="reservation-status @activeStatus">
            @status
        </div>
        @string.Format("Date : {0:ddd, MMMM d, yyyy}", Model.ReservationDetails.Date)
    </div>
    <div id="reservations-date-adm">
        <div>
            <p>@string.Format("Name : {0} {1}", @Model.User.FirstName, @Model.User.Surname)</p>
        </div>
    </div>
    <div id="reservation-details-adm">
        <div>
            <div>
                <p>
                    @string.Format("Email: {0}", Model.User.Email)
                </p>
            </div>
            <div>
                <p>@string.Format("Phone : {0}", @Model.User.Phone)</p>
            </div>
        </div>
        @if (Model.ReservationDetails.Status == 0)
        {
            <div id="wrapper-accepting">
                @Html.HiddenFor(m => m.ReservationDetails.ExcursionId)
                @using (Html.BeginForm("DeclineReservation", "ExcursionAdministratorPanel", new { reservationId = Model.ReservationDetails.ReservationId, excursionId = Model.ReservationDetails.ExcursionId }, FormMethod.Post, new { @class = "accepting-form" }))
                {
                    <input type="submit" value="Decline">
                }
                @using (Html.BeginForm("AcceptReservation", "ExcursionAdministratorPanel", new { reservationId = Model.ReservationDetails.ReservationId, excursionId = Model.ReservationDetails.ExcursionId }, FormMethod.Post, new { @class = "accepting-form", @id = "accept" }))
                {
                    <input type="submit" value="Accept">
                }
            </div>
        }
    </div>
</div>