CityCenter/CityCenter.WebUI.Frontend/Controllers/Error404Controller.cs
using System.Web.Mvc;

namespace CityCenter.WebUI.Frontend.Controllers
{
    public class Error404Controller : Controller
    {
        [HttpGet]
        public ActionResult Error404()
        {
            Response.StatusCode = 404;
            Response.TrySkipIisCustomErrors = true;
            return View();
        }
    }
}

CityCenter/CityCenter.WebUI.Frontend/Controllers/HotelAdministratorPanelController.cs
using System;
using System.Web;
using System.Web.Mvc;
using CityCenter.BLL.Abstract;
using CityCenter.Entities;
using CityCenter.WebUI.Abstract;
using CityCenter.WebUI.Frontend.Code;
using CityCenter.WebUI.Frontend.Models.Helper;
using CityCenter.WebUI.Frontend.Models.Hotel;
using CityCenter.WebUI.Frontend.Models.Panel;
using PagedList;

namespace CityCenter.WebUI.Frontend.Controllers
{
    [AuthorizeOrThrow404("HotelAdmin")]
    public class HotelAdministratorPanelController : Controller
    {
        #region Fields

        private readonly IUsersManager _usersManager;
        private readonly IHotelsManager _hotelsManager;
        private readonly ISecurityManager _securityManager;
        private readonly IEmailManager _emailManager;

        #endregion

        #region Constructor

        public HotelAdministratorPanelController(IUsersManager usersManager, IHotelsManager hotelsManager, ISecurityManager securityManager, IEmailManager emailManager)
        {
            _usersManager = usersManager;
            _hotelsManager = hotelsManager;
            _securityManager = securityManager;
            _emailManager = emailManager;
        }

        #endregion

        #region WebActions

        [HttpGet]
        public ActionResult Panel()
        {
            return View();
        }

        [HttpGet]
        public ActionResult EditHotelContent(int hotelId)
        {
            #region Validation

            var userId = _securityManager.GetCurrentUserId();
            if (!_securityManager.IsUserAdministratorOfHotel(userId, hotelId))
            {
                throw new HttpException(404, "HTTP/1.1 404 Not Found");
            }

            #endregion

            var hotelDiscriptionModel = new HotelDescriptionModel
            {
                HotelName = _hotelsManager.GetHotelById(hotelId).Name,
                HotelDescription = _hotelsManager.GetHotelDescriptionById(hotelId)
            };

            ViewBag.CountOfPendingReservation = _hotelsManager.GetPendingReservationCountByHotelId(hotelId);

            return PartialView("_EditHotelContent", hotelDiscriptionModel);
        }
        
        [HttpPost]
        public ActionResult EditHotelContent(HotelDescriptionModel model)
        {
            if (ModelState.IsValid)
            {
                _hotelsManager.UpdateHotelDescription(model.HotelDescription);
                _hotelsManager.UpdateHotelName(model.HotelName, model.HotelDescription.HotelId);
                return RedirectToAction("Panel");
            }
            return PartialView("_EditHotelContent");
        }

        [HttpGet]
        public FileContentResult GetHotelImage(int hotelId)
        {
            var desc = _hotelsManager.GetHotelDescriptionById(hotelId);
            return File(desc.Photo, MimeMapping.GetMimeMapping(desc.PhotoExtension));
        }

        [HttpPost]
        public ActionResult UploadNewImage(int hotelId, HttpPostedFileBase image)
        {
            if (image != null)
            {
                var hotelDescription = _hotelsManager.GetHotelDescriptionById(hotelId);
                hotelDescription.Photo = new byte[image.ContentLength];
                hotelDescription.PhotoExtension = image.ContentType;
                image.InputStream.Read(hotelDescription.Photo, 0, image.ContentLength);
                _hotelsManager.UpdateHotelImage(hotelDescription);
            }
            return RedirectToAction("EditHotelContent", new { hotelId });
        }

        [HttpGet]
        public ActionResult PendingReservations(int hotelId, int page = 1)
        {
            #region Validation

            var userId = _securityManager.GetCurrentUserId();

            if (!_securityManager.IsUserAdministratorOfHotel(userId, hotelId))
            {
                throw new HttpException(404, "HTTP/1.1 404 Not Found");
            }

            #endregion

            var pagedListModel = new PagedListModel()
            {
                Page = page,
                PageSize = 2,
                TotalItems = _hotelsManager.GetPendingReservationCountByHotelId(hotelId)
            };

            ViewBag.TotalItems = pagedListModel.TotalItems;
            ViewBag.PageSize = pagedListModel.PageSize;
            ViewBag.CountOfPendingReservation = pagedListModel.TotalItems;

            #region Paging Validation

            if (page < 1)
            {
                return RedirectToAction("PendingReservations");
            }
            if (page != 1 && (page - 1) * pagedListModel.PageSize >= pagedListModel.TotalItems)
            {
                return RedirectToAction("PendingReservations", new
                {
                    page = (int)Math.Ceiling((double)pagedListModel.TotalItems / pagedListModel.PageSize)
                });
            }

            #endregion

            var reservationEntities = _hotelsManager.GetPendingHotelReservationByHotelId(hotelId, pagedListModel.Page,
                pagedListModel.PageSize);

            var pagedList = new StaticPagedList<HotelReservationDetails>(reservationEntities, page, pagedListModel.PageSize,
                pagedListModel.TotalItems);

            var model = new AdminHotelReservationDetailsModel()
            {
                ReservationDetails = pagedList,
                HotelId = hotelId
            };

            return View(model);
        }

        [HttpGet]
        public ActionResult AcceptedReservations(int hotelId, int page = 1)
        {
            #region Validation

            var userId = _securityManager.GetCurrentUserId();

            if (!_securityManager.IsUserAdministratorOfHotel(userId, hotelId))
            {
                throw new HttpException(404, "HTTP/1.1 404 Not Found");
            }

            #endregion

            var pagedListModel = new PagedListModel()
            {
                Page = page,
                PageSize = 3,
                TotalItems = _hotelsManager.GetReservationCountByHotelId(hotelId)
            };

            ViewBag.TotalItems = pagedListModel.TotalItems;
            ViewBag.PageSize = pagedListModel.PageSize;
            ViewBag.CountOfPendingReservation = _hotelsManager.GetPendingReservationCountByHotelId(hotelId);

            #region Paging Validation

            if (page < 1)
            {
                return RedirectToAction("PendingReservations");
            }
            if (page != 1 && (page - 1) * pagedListModel.PageSize >= pagedListModel.TotalItems)
            {
                return RedirectToAction("PendingReservations", new { page = (int)Math.Ceiling((double)pagedListModel.TotalItems / pagedListModel.PageSize) });
            }

            #endregion

            var reservationEntities = _hotelsManager.GetHotelReservationByHotelId(hotelId, pagedListModel.Page,
                pagedListModel.PageSize);

            var pagedList = new StaticPagedList<HotelReservationDetails>(reservationEntities, page, pagedListModel.PageSize,
                pagedListModel.TotalItems);

            var model = new AdminHotelReservationDetailsModel()
            {
                ReservationDetails = pagedList,
                HotelId = hotelId
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult AcceptBook(int reservationId, int hotelId)
        {
            var hotelName = _hotelsManager.GetHotelById(hotelId).Name;
            _hotelsManager.AcceptReservation(reservationId);
            SendEmailReservationNotification(hotelName, reservationId, reservationStatus: "Accepted");
            return RedirectToAction("PendingReservations", new { hotelId });
        }

        [HttpPost]
        public ActionResult DeclineBook(int reservationId, int hotelId)
        {
            var hotelName = _hotelsManager.GetHotelById(hotelId).Name;
            _hotelsManager.DeclineReservation(reservationId);
            SendEmailReservationNotification(hotelName, reservationId, reservationStatus: "Declined");
            return RedirectToAction("PendingReservations", new { hotelId });
        }

        #endregion

        #region Helper

        private void SendEmailReservationNotification(string hotelName, int reservationId, string reservationStatus)
        {
            var userId = _usersManager.GetUserIdByReservationId(reservationId);
            var user = _usersManager.GetUserById(userId);

            var mailSubject = "Reservation Notification";
            var mailBody = string.Format(
                "<div style=\"font-size:16px;\">Dear {0} {1}.<br/>"
                + "Your Reservation at hotel {2} was : {3}",
                user.FirstName, user.Surname, hotelName, reservationStatus);

            _emailManager.SendEmail(user.Email, mailSubject, mailBody);
        }

        #endregion
    }
}

CityCenter/CityCenter.WebUI.Frontend/Controllers/MainPageController.cs
using System.Web.Mvc;
using CityCenter.BLL.Abstract;
using CityCenter.WebUI.Frontend.Models;
using CityCenter.WebUI.Frontend.Models.Account;

namespace CityCenter.WebUI.Frontend.Controllers
{
    public class MainPageController : Controller
    {
        #region Fields

        private readonly IUsersManager _userManager;

        #endregion

        #region Constructor

        public MainPageController(IUsersManager userManager)
        {
            _userManager = userManager;
        }

        #endregion

        #region WebActions

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Map()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Feedback()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Feedback(FeedbackModel model)
        {
            if (ModelState.IsValid)
            {                
                _userManager.InsertUserFeedback(model.Login, model.Email, model.Message);
                return View("Index");
            }
            return View("Feedback");
        }

        #endregion
    }
}

CityCenter/CityCenter.WebUI.Frontend/Views/Shared/Error404.cshtml
@using System.Web.Optimization
@{
    ViewBag.Title = "Error 404";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section style{
    @Styles.Render("~/Content/error-404")
}

<div id="wrapper-error-page">
    <div id="wrapper-error">
        <a href="@Url.Action("Index","MainPage")">
            <div id="back-to-home">
            </div>
        </a>
    </div>
</div>

CityCenter/CityCenter.WebUI.Frontend/Views/Shared/RequetSend.cshtml
@using System.Web.Optimization

@{
    ViewBag.Title = "RequestSend";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section style {

    @Styles.Render("~/Content/confirm")
}

<div id="wrapper-confirm">
    <div id="wrapper-message">
        <div id="message">
            <p>
                Your request sent.
            </p>
            <p>

            </p>
            <a href="@Url.Action("Index", "MainPage")" id="back-to-main">
                Go to main page
            </a>
        </div>
    </div>
</div>

CityCenter/CityCenter.WebUI.Frontend/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@using CityCenter.WebUI.Abstract
@using CityCenter.WebUI.Frontend.Code

@{
    Layout = null;
    var securityManager = DependencyResolver.Current.GetService<ISecurityManager>();
    var username = securityManager.GetCurrentUser();
    var register = "Sign up";
    var logIn = "Log in";
    var logOut = "Log out";

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="City Center guide for tourists">
    <meta name="author" content="City Center Team">
    <link rel="shortcut icon" href="~/Content/images/inner-logo.ico" type="image/x-icon" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/main")
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("style", false)
    @RenderSection("scripts", false)
    @RenderSection("ico", false)
</head>
<body>
    <div id="wrapper-header">
        <div id="wrapper-top-header">
            <div id="wrapper-double-header">
                <div id="sign-up-in">
                    <a class="sign @(username == "" ? @Html.ActivePage("SignUp", "Account") : null)" href="@(username == "" ? Url.Action("SignUp", "Account") : Url.Action("Panel", "UserPanel"))" title="@(username == "" ? null : "Go to panel")">@(username == "" ? register : username) </a>
                    <span id="slash">|</span>
                    <a class="sign @(username == "" ? @Html.ActivePage("LogIn", "Account") : null)" id="login" href="@(username == "" ? Url.Action("LogIn", "Account") : Url.Action("LogOut", "Account"))">@(username == "" ? logIn : logOut)</a>
                </div>
            </div>
        </div>
        <div id="max-wrapper-header">
            <header id="header">
                <a href="@Url.Action("Index", "MainPage")">
                    <div id="logo">
                    </div>
                </a>
                <nav id="menu">
                    <ul class="menu-list">
                        <li>
                            <a href="@Url.Action("Index", "MainPage")" class="@Html.ActivePage("Index", "MainPage")">Main</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Hotels", "Hotels")" class="@Html.ActivePage("Hotels", "Hotels")">Hotels</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Excursions", "Excursions")" class="@Html.ActivePage("Excursions", "Excursions")">Excursions</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Map", "MainPage")" class="@Html.ActivePage("Map", "MainPage")">Map</a>
                        </li>
                    </ul>
                </nav>
            </header>
        </div>
    </div>
    <section>
        <div>
            @RenderBody()
        </div>
    </section>
    <div id="wrapper-footer-nav">
        <nav id="footer-nav">
            <div>
                <nav id="footer-menu">
                    <ul class="menu-list">
                        <li>
                            <a href="@Url.Action("Index", "MainPage")" class="@Html.ActivePage("Index", "MainPage")">Main</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Hotels", "Hotels")" class="@Html.ActivePage("Hotels", "Hotels")">Hotels</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Excursions", "Excursions")" class="@Html.ActivePage("Excursions", "Excursions")">Excursions</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Map", "MainPage")" class="@Html.ActivePage("Map", "MainPage")">Map</a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div>
                <a href="@(username == "" ? Url.Action("Feedback", "MainPage") : Url.Action("Feedback", "UserPanel"))">
                    <div id="feedback">
                    </div>
                </a>
            </div>
            <div id="contacts">
                <article id="contacts-info">
                    <p>
                        City Center
                    </p>
                    <p>
                        Phone: +00 (123) 456 7890
                    </p>
                    <p>
                        e-mail: lviv.city.center@gmail.com
                    </p>
                </article>
            </div>
        </nav>
    </div>
    <div id="wrapper-footer">
        <footer id="footer">
            <p id="copyright">
                Copyright © 2015 City Center
            </p>
        </footer>
    </div>
</body>
</html>

CityCenter/CityCenter.WebUI.Frontend/Views/Shared/_PanelLayout.cshtml
@using System.Web.Optimization
@using CityCenter.WebUI.Abstract
@using CityCenter.WebUI.Frontend.Code

@{
    Layout = null;
    var securityManager = DependencyResolver.Current.GetService<ISecurityManager>();
    var username = securityManager.GetCurrentUser();
}

<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="City Center guide for tourists">
    <meta name="author" content="City Center Team">
    <title>@ViewBag.Title</title>
    <link href="~/Content/styles/panel-style.css" rel="stylesheet" />
    <link rel="shortcut icon" href="~/Content/images/inner-logo.ico" type="image/x-icon" />
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("style", false)
    @RenderSection("scripts", false)
    @RenderSection("ico", false)
</head>
<body>
    <div id="wrapper-panel-header">
        <header id="header">
            <a href="@Url.Action("Panel", "UserPanel")">
                <div id="logo">
                </div>
            </a>
            <div id="sign-up-in">
                @if (User.IsInRole("ExcursionAdmin"))
                {
                    <a class="sign" href="@Url.Action("Panel", "ExcursionAdministratorPanel")">Excursions</a>
                    <span class="slash">|</span>
                }
                @if (User.IsInRole("HotelAdmin"))
                {
                    <a class="sign" href="@Url.Action("Panel", "HotelAdministratorPanel")">Hotels</a>
                    <span class="slash">|</span>
                }
                <a class="sign @(username == "" ? @Html.ActivePage("SignUp", "Account") : null)" href="@(Url.Action("Panel", "UserPanel"))">@username</a>
                <span class="slash">|</span>
                <a class="sign" href="@(Url.Action("Index", "MainPage"))">Go to main page</a>
                <span class="slash">|</span>
                <a class="sign @(username == "" ? @Html.ActivePage("LogIn", "Account") : null)" id="login" href="@(Url.Action("LogOut", "Account"))">Log out</a>
            </div>

        </header>
    </div>


    <div id="wrapper-all-body">
        @RenderBody()
    </div>
    <div id="wrapper-footer">
        <footer id="footer">
            <p id="copyright">
                Copyright © 2015 City Center
            </p>
        </footer>
    </div>
</body>
</html>