CityCenter/CityCenter.WebUI.Frontend/Models/Panel/AdminExcursionReservationDetailsModel.cs
using PagedList;

namespace CityCenter.WebUI.Frontend.Models.Panel
{
    public class AdminExcursionReservationDetailsModel
    {
        public StaticPagedList<ExcursionReservationDetailsModel> ReservationDetails { get; set; }

        public int ExcursionId { get; set; }
    }
}

CityCenter/CityCenter.WebUI.Frontend/Models/Panel/AdminHotelReservationDetailsModel.cs
using CityCenter.Entities;
using PagedList;

namespace CityCenter.WebUI.Frontend.Models.Panel
{
    public class AdminHotelReservationDetailsModel
    {
        public StaticPagedList<HotelReservationDetails> ReservationDetails { get; set; }

        public int HotelId { get; set; }
    }
}

CityCenter/CityCenter.WebUI.Frontend/Models/Panel/ExcursionAdministratorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CityCenter.Entities;

namespace CityCenter.WebUI.Frontend.Models.Panel
{
    public class ExcursionAdministratorModel
    {
        public List<Role> UserRoles { get; set; }

        public IList<SelectListItem> CurrentExcursion { get; set; }

        [DisplayName("Excursion")]
        [Required]
        public int SelectedExcursionId { get; set; }
    }
}

CityCenter/CityCenter.WebUI.Frontend/Models/Panel/ExcursionReservationDetailsModel.cs
using CityCenter.Entities;

namespace CityCenter.WebUI.Frontend.Models.Panel
{
    public class ExcursionReservationDetailsModel
    {
        public ExcursionReservationDetails ReservationDetails { get; set; }

        public User User { get; set; }
    }
}

CityCenter/CityCenter.WebUI.Frontend/Models/Panel/HotelAdministratorPanelModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using CityCenter.Entities;

namespace CityCenter.WebUI.Frontend.Models.Panel
{
    public class HotelAdministratorPanelModel
    {
        public List<Role> UserRoles { get; set; }

        public IList<SelectListItem> CurrentHotels { get; set; }

        [DisplayName("Hotel")]
        [Required]
        public int SelectedHotelId { get; set; }
    }
}

CityCenter/CityCenter.WebUI.Frontend/Models/Panel/HotelReservationDetailsModel.cs
using CityCenter.Entities;

namespace CityCenter.WebUI.Frontend.Models.Panel
{
    public class HotelReservationDetailsModel
    {
        public HotelReservationDetails ReservationDetails { get; set; }
    }
}

CityCenter/CityCenter.WebUI.Frontend/Models/Panel/PanelUserInfoModel.cs
using System.ComponentModel.DataAnnotations;

namespace CityCenter.WebUI.Frontend.Models.Panel
{
    public class PanelUserInfoModel
    {
        [Required(ErrorMessage = "Name is required")]
        [StringLength(30, ErrorMessage = "Length should not exceed 30")]
        [RegularExpression(@"^[a-zA-Zа-яА-ЯіІ]{1,30}", ErrorMessage = "Invalid first name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Surname is required")]
        [StringLength(30, ErrorMessage = "Length should not exceed 30")]
        [RegularExpression(@"^[a-zA-Zа-яА-ЯіІ]{1,30}", ErrorMessage = "Invalid surname")]
        public string Surname { get; set; }

        [Required(ErrorMessage = "Phone is required")]
        [StringLength(13, ErrorMessage = "Length should be 13")]
        [RegularExpression(@"^\+[1-9]{1}[0-9]{11}$", ErrorMessage = "Invalid Phone")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Email is required")]
        [StringLength(50, ErrorMessage = "Length should not exceed 50")]
        [RegularExpression(@"^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$", ErrorMessage = "Invalid email")]
        public string Email { get; set; }
    }
}

CityCenter/CityCenter.WebUI.Frontend/Controllers/HapNavigationController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using CityCenter.BLL.Abstract;
using CityCenter.WebUI.Abstract;
using CityCenter.WebUI.Frontend.Models.Panel;

namespace CityCenter.WebUI.Frontend.Controllers
{
    public class HapNavigationController : Controller
    {
        #region Fields

        private readonly IUsersManager _userManager;
        private readonly IHotelsManager _hotelManager;
        private readonly ISecurityManager _securityManager;

        #endregion

        #region Constructor

        public HapNavigationController(IUsersManager usersManager, IHotelsManager hotelsManager, ISecurityManager securityManager)
        {
            _userManager = usersManager;
            _hotelManager = hotelsManager;
            _securityManager = securityManager;
        }

        #endregion

        #region WebActions

        [HttpGet]
        [ChildActionOnly]
        public ActionResult Menu(string categoty = null)
        {
            var userId = _securityManager.GetCurrentUserId();
            var model = new HotelAdministratorPanelModel()
            {
                UserRoles = _userManager.GetUserRoles(userId),
                CurrentHotels = ConvertToSelectListItem()
            };

            return PartialView("_HotelsMenu", model);
        }

        #endregion

        #region Helper

        private List<SelectListItem> ConvertToSelectListItem()
        {
            var userId = _securityManager.GetCurrentUserId();
            var hotel = _hotelManager.GetHotelsByAdminId(userId);
            return hotel.Select(h => new SelectListItem() { Text = h.Name, Value = h.Id.ToString() }).ToList();
        }

        #endregion
    }
}

CityCenter/CityCenter.WebUI.Frontend/Controllers/HotelAdministratorPanelController.cs
using System;
using System.Web;
using System.Web.Mvc;
using CityCenter.BLL.Abstract;
using CityCenter.Entities;
using CityCenter.WebUI.Abstract;
using CityCenter.WebUI.Frontend.Code;
using CityCenter.WebUI.Frontend.Models.Helper;
using CityCenter.WebUI.Frontend.Models.Hotel;
using CityCenter.WebUI.Frontend.Models.Panel;
using PagedList;

namespace CityCenter.WebUI.Frontend.Controllers
{
    [AuthorizeOrThrow404("HotelAdmin")]
    public class HotelAdministratorPanelController : Controller
    {
        #region Fields

        private readonly IUsersManager _usersManager;
        private readonly IHotelsManager _hotelsManager;
        private readonly ISecurityManager _securityManager;
        private readonly IEmailManager _emailManager;

        #endregion

        #region Constructor

        public HotelAdministratorPanelController(IUsersManager usersManager, IHotelsManager hotelsManager, ISecurityManager securityManager, IEmailManager emailManager)
        {
            _usersManager = usersManager;
            _hotelsManager = hotelsManager;
            _securityManager = securityManager;
            _emailManager = emailManager;
        }

        #endregion

        #region WebActions

        [HttpGet]
        public ActionResult Panel()
        {
            return View();
        }

        [HttpGet]
        public ActionResult EditHotelContent(int hotelId)
        {
            #region Validation

            var userId = _securityManager.GetCurrentUserId();
            if (!_securityManager.IsUserAdministratorOfHotel(userId, hotelId))
            {
                throw new HttpException(404, "HTTP/1.1 404 Not Found");
            }

            #endregion

            var hotelDiscriptionModel = new HotelDescriptionModel
            {
                HotelName = _hotelsManager.GetHotelById(hotelId).Name,
                HotelDescription = _hotelsManager.GetHotelDescriptionById(hotelId)
            };

            ViewBag.CountOfPendingReservation = _hotelsManager.GetPendingReservationCountByHotelId(hotelId);

            return PartialView("_EditHotelContent", hotelDiscriptionModel);
        }
        
        [HttpPost]
        public ActionResult EditHotelContent(HotelDescriptionModel model)
        {
            if (ModelState.IsValid)
            {
                _hotelsManager.UpdateHotelDescription(model.HotelDescription);
                _hotelsManager.UpdateHotelName(model.HotelName, model.HotelDescription.HotelId);
                return RedirectToAction("Panel");
            }
            return PartialView("_EditHotelContent");
        }

        [HttpGet]
        public FileContentResult GetHotelImage(int hotelId)
        {
            var desc = _hotelsManager.GetHotelDescriptionById(hotelId);
            return File(desc.Photo, MimeMapping.GetMimeMapping(desc.PhotoExtension));
        }

        [HttpPost]
        public ActionResult UploadNewImage(int hotelId, HttpPostedFileBase image)
        {
            if (image != null)
            {
                var hotelDescription = _hotelsManager.GetHotelDescriptionById(hotelId);
                hotelDescription.Photo = new byte[image.ContentLength];
                hotelDescription.PhotoExtension = image.ContentType;
                image.InputStream.Read(hotelDescription.Photo, 0, image.ContentLength);
                _hotelsManager.UpdateHotelImage(hotelDescription);
            }
            return RedirectToAction("EditHotelContent", new { hotelId });
        }

        [HttpGet]
        public ActionResult PendingReservations(int hotelId, int page = 1)
        {
            #region Validation

            var userId = _securityManager.GetCurrentUserId();

            if (!_securityManager.IsUserAdministratorOfHotel(userId, hotelId))
            {
                throw new HttpException(404, "HTTP/1.1 404 Not Found");
            }

            #endregion

            var pagedListModel = new PagedListModel()
            {
                Page = page,
                PageSize = 2,
                TotalItems = _hotelsManager.GetPendingReservationCountByHotelId(hotelId)
            };

            ViewBag.TotalItems = pagedListModel.TotalItems;
            ViewBag.PageSize = pagedListModel.PageSize;
            ViewBag.CountOfPendingReservation = pagedListModel.TotalItems;

            #region Paging Validation

            if (page < 1)
            {
                return RedirectToAction("PendingReservations");
            }
            if (page != 1 && (page - 1) * pagedListModel.PageSize >= pagedListModel.TotalItems)
            {
                return RedirectToAction("PendingReservations", new
                {
                    page = (int)Math.Ceiling((double)pagedListModel.TotalItems / pagedListModel.PageSize)
                });
            }

            #endregion

            var reservationEntities = _hotelsManager.GetPendingHotelReservationByHotelId(hotelId, pagedListModel.Page,
                pagedListModel.PageSize);

            var pagedList = new StaticPagedList<HotelReservationDetails>(reservationEntities, page, pagedListModel.PageSize,
                pagedListModel.TotalItems);

            var model = new AdminHotelReservationDetailsModel()
            {
                ReservationDetails = pagedList,
                HotelId = hotelId
            };

            return View(model);
        }

        [HttpGet]
        public ActionResult AcceptedReservations(int hotelId, int page = 1)
        {
            #region Validation

            var userId = _securityManager.GetCurrentUserId();

            if (!_securityManager.IsUserAdministratorOfHotel(userId, hotelId))
            {
                throw new HttpException(404, "HTTP/1.1 404 Not Found");
            }

            #endregion

            var pagedListModel = new PagedListModel()
            {
                Page = page,
                PageSize = 3,
                TotalItems = _hotelsManager.GetReservationCountByHotelId(hotelId)
            };

            ViewBag.TotalItems = pagedListModel.TotalItems;
            ViewBag.PageSize = pagedListModel.PageSize;
            ViewBag.CountOfPendingReservation = _hotelsManager.GetPendingReservationCountByHotelId(hotelId);

            #region Paging Validation

            if (page < 1)
            {
                return RedirectToAction("PendingReservations");
            }
            if (page != 1 && (page - 1) * pagedListModel.PageSize >= pagedListModel.TotalItems)
            {
                return RedirectToAction("PendingReservations", new { page = (int)Math.Ceiling((double)pagedListModel.TotalItems / pagedListModel.PageSize) });
            }

            #endregion

            var reservationEntities = _hotelsManager.GetHotelReservationByHotelId(hotelId, pagedListModel.Page,
                pagedListModel.PageSize);

            var pagedList = new StaticPagedList<HotelReservationDetails>(reservationEntities, page, pagedListModel.PageSize,
                pagedListModel.TotalItems);

            var model = new AdminHotelReservationDetailsModel()
            {
                ReservationDetails = pagedList,
                HotelId = hotelId
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult AcceptBook(int reservationId, int hotelId)
        {
            var hotelName = _hotelsManager.GetHotelById(hotelId).Name;
            _hotelsManager.AcceptReservation(reservationId);
            SendEmailReservationNotification(hotelName, reservationId, reservationStatus: "Accepted");
            return RedirectToAction("PendingReservations", new { hotelId });
        }

        [HttpPost]
        public ActionResult DeclineBook(int reservationId, int hotelId)
        {
            var hotelName = _hotelsManager.GetHotelById(hotelId).Name;
            _hotelsManager.DeclineReservation(reservationId);
            SendEmailReservationNotification(hotelName, reservationId, reservationStatus: "Declined");
            return RedirectToAction("PendingReservations", new { hotelId });
        }

        #endregion

        #region Helper

        private void SendEmailReservationNotification(string hotelName, int reservationId, string reservationStatus)
        {
            var userId = _usersManager.GetUserIdByReservationId(reservationId);
            var user = _usersManager.GetUserById(userId);

            var mailSubject = "Reservation Notification";
            var mailBody = string.Format(
                "<div style=\"font-size:16px;\">Dear {0} {1}.<br/>"
                + "Your Reservation at hotel {2} was : {3}",
                user.FirstName, user.Surname, hotelName, reservationStatus);

            _emailManager.SendEmail(user.Email, mailSubject, mailBody);
        }

        #endregion
    }
}

CityCenter/CityCenter.WebUI.Frontend/Views/HotelAdministratorPanel/AcceptedReservations.cshtml
@using System.Web.Optimization
@using PagedList.Mvc
@model CityCenter.WebUI.Frontend.Models.Panel.AdminHotelReservationDetailsModel
@{
    ViewBag.Title = "Accepted Reservations";
    Layout = "~/Views/HotelAdministratorPanel/_MenuLayout.cshtml";
    var totalItems = ViewBag.TotalItems;
    var pageSize = ViewBag.PageSize;
}

@section style{
    @Styles.Render("~/Content/show-reservations")
    @Styles.Render("~/Content/paged-list")
}

<div id="wrapper-panel-body">
    <div id="wrapper-panel-body-func">
        @Html.Partial("_Navigation", new ViewDataDictionary { { "id", @Model.HotelId }, { "PendingCount", ViewBag.CountOfPendingReservation } })
        <div id="wrapper-panel-func">
            @if (@Model.ReservationDetails.Count != 0)
            {
                foreach (var reservation in @Model.ReservationDetails)
                {
                    @Html.Partial("_Reservations", reservation)
                }
                if (totalItems > pageSize)
                {
                    @Html.PagedListPager(Model.ReservationDetails, page => @Url.Action("AcceptedReservations", "HotelAdministratorPanel", new { hotelId = @Model.HotelId, page }))
                }
            }
            else
            {
                <h3>No reservations</h3>
            }
        </div>
    </div>
</div>

CityCenter/CityCenter.WebUI.Frontend/Views/HotelAdministratorPanel/Panel.cshtml
@model CityCenter.WebUI.Frontend.Models.Panel.HotelAdministratorPanelModel

@{
    ViewBag.Title = "Panel";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}
<div id="wrapper-menu">
    @{ Html.RenderAction("Menu", "HapNavigation");}
</div>

CityCenter/CityCenter.WebUI.Frontend/Views/HotelAdministratorPanel/PendingReservations.cshtml
@using System.Web.Optimization
@using PagedList.Mvc
@model CityCenter.WebUI.Frontend.Models.Panel.AdminHotelReservationDetailsModel
@{
    ViewBag.Title = "Pending Reservations";
    Layout = "~/Views/HotelAdministratorPanel/_MenuLayout.cshtml";
    var totalItems = ViewBag.TotalItems;
    var pageSize = ViewBag.PageSize;
}

@section style{
    @Styles.Render("~/Content/show-reservations")
    @Styles.Render("~/Content/paged-list")
}

<div id="wrapper-panel-body">
    <div id="wrapper-panel-body-func">
        @Html.Partial("_Navigation", new ViewDataDictionary { { "id", @Model.HotelId }, { "PendingCount", ViewBag.CountOfPendingReservation } })
        <div id="wrapper-panel-func">
            @if (@Model.ReservationDetails.Count != 0)
            {
                foreach (var reservation in @Model.ReservationDetails)
                {
                    @Html.Partial("_Reservations", reservation)
                }
                if (totalItems > pageSize)
                {
                    @Html.PagedListPager(Model.ReservationDetails, page => @Url.Action("PendingReservations", "HotelAdministratorPanel", new { hotelId = Model.HotelId, page }))
                }
            }
            else
            {
                <h3>No reservations</h3>
            }
        </div>
    </div>
</div>

CityCenter/CityCenter.WebUI.Frontend/Views/HotelAdministratorPanel/_EditHotelContent.cshtml
@using System.Web.Optimization
@model CityCenter.WebUI.Frontend.Models.Hotel.HotelDescriptionModel
@{
    ViewBag.Title = "EditHotelContent";
    Layout = "~/Views/HotelAdministratorPanel/_MenuLayout.cshtml";
}

@section style{

    @Styles.Render("~/Content/edit-content")
}

<div id="wrapper-panel-body">
    <div id="wrapper-panel-body-func">
        @Html.Partial("_Navigation", new ViewDataDictionary { { "id", @Model.HotelDescription.HotelId }, { "PendingCount", ViewBag.CountOfPendingReservation } })
        <div id="wrapper-panel-func">
            @using (Html.BeginForm("EditHotelContent", "HotelAdministratorPanel", FormMethod.Post, new { @id = "request-form" }))
            {
                <div id="wrapper-txt-box">
                    <div class="txt-box">
                        @Html.LabelFor(m => m.HotelName)
                        @Html.TextBoxFor(m => m.HotelName)
                    </div>
                    <div class="txt-box">
                        @Html.LabelFor(m => m.HotelDescription.Address)
                        @Html.TextBoxFor(m => m.HotelDescription.Address)
                    </div>
                    <div class="txt-box">
                        @Html.LabelFor(m => m.HotelDescription.Phone)
                        @Html.TextBoxFor(m => m.HotelDescription.Phone)
                    </div>
                    <div class="txt-box">
                        @Html.LabelFor(m => m.HotelDescription.Site)
                        @Html.TextBoxFor(m => m.HotelDescription.Site)
                    </div>
                </div>
                <div id="txt-area-head">
                    @Html.LabelFor(m => m.HotelDescription.Header)
                    @Html.TextAreaFor(m => m.HotelDescription.Header)
                </div>
                <div id="txt-area-desc">
                    @Html.LabelFor(m => m.HotelDescription.Description)
                    @Html.TextAreaFor(m => m.HotelDescription.Description)
                </div>
                @Html.HiddenFor(m => m.HotelDescription.HotelId)
                <input type="submit" id="edit-button" name="edit-button" value="Edit" />
            }
            @using (Html.BeginForm("UploadNewImage", "HotelAdministratorPanel", new { hotelId = @Model.HotelDescription.HotelId }, FormMethod.Post, new { enctype = "multipart/form-data", @id = "choise-img" }))
            {
                <img src="@Url.Action("GetHotelImage", "Hotels", new {@Model.HotelDescription.HotelId})" alt="@Model.HotelName" />
                <input type="file" name="Image" />
                <input type="submit" value="Update Photo" />
            }
        </div>
    </div>
</div>

CityCenter/CityCenter.WebUI.Frontend/Views/HotelAdministratorPanel/_MenuLayout.cshtml
@{
    ViewBag.Title = "Panel";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}
@section scripts{
    @RenderSection("scripts", false)
}
@section style{
    @RenderSection("style", false)

}

<div id="wrapper-menu">
    @{ Html.RenderAction("Menu", "HapNavigation");}
</div>
@RenderBody()

CityCenter/CityCenter.WebUI.Frontend/Views/HotelAdministratorPanel/_Navigation.cshtml
@using CityCenter.WebUI.Frontend.Code
@{
    var hotelId = (int)ViewData["id"];
    var countOfPendingReservation = (int)ViewData["PendingCount"];
}
<div id="wrapper-panel-button">
    <a href="@Url.Action("EditHotelContent", "HotelAdministratorPanel", new { hotelId })">
        <div class="panel-buttons @Html.ActivePage("EditHotelContent", "HotelAdministratorPanel")">
            Edit Hotel Content
        </div>
    </a>

    <a href="@Url.Action("AcceptedReservations", "HotelAdministratorPanel", new {hotelId })">
        <div class="panel-buttons @Html.ActivePage("AcceptedReservations", "HotelAdministratorPanel")">
            Reservations
        </div>
    </a>
    <a href="@Url.Action("PendingReservations", "HotelAdministratorPanel", new { hotelId })">
        <div class="panel-buttons @Html.ActivePage("PendingReservations", "HotelAdministratorPanel")">
            Pending Reservations @if (countOfPendingReservation != 0)
            {
                <span id="count-reservation">+@countOfPendingReservation</span>

            }
        </div>
    </a>
</div>

CityCenter/CityCenter.WebUI.Frontend/Views/HotelAdministratorPanel/_Reservations.cshtml
@using System.Globalization
@model CityCenter.Entities.HotelReservationDetails

@{
    var parking = "";
    var pool = "";
    var sauna = "";
    var tennisCourt = "";
    var gym = "";
    var absent = "";
    var status = "";
    var activeStatus = "";
    var dateCount = Model.EndDate.Subtract(Model.BeginDate);
    var price = dateCount.Days * Model.Price;
}
<div id="@(Model.Status == 0 ? "wrapper-reservations-body-with-button" : "wrapper-reservations-body")">
    <div id="reservation-header">
        @switch (Model.Status)
        {
            case 0:
                status = "Pending";
                break;
            case 1:
                status = "Decline";
                break;
            case 2:
                if (Model.BeginDate > DateTime.Now)
                {
                    status = "In Future";
                }
                if (Model.EndDate < DateTime.Now)
                {
                    status = "Finished";
                }
                if (Model.BeginDate < DateTime.Now && Model.EndDate > DateTime.Now)
                {
                    status = "In Progress";
                }
                break;
            default:
                status = "";
                break;
        }
        @switch (status)
        {
            case "Pending":
                activeStatus = "pending";
                break;
            case "Decline":
                activeStatus = "decline";
                break;
            case "In Future":
                activeStatus = "in-future";
                break;
            case "Finished":
                activeStatus = "finished";
                break;
            case "In Progress":
                activeStatus = "in-progress";
                break;
        }
        <div class="reservation-status @activeStatus">
            @status
        </div>
        @Model.HotelName
    </div>
    <div id="reservations-date">
        <div>
            <p>Begin Date: @string.Format("{0:ddd, MMMM d, yyyy}", Model.BeginDate)</p>
        </div>
        <div id="end-date">
            <p>End Date: @string.Format("{0:ddd, MMMM d, yyyy}", Model.EndDate)</p>
        </div>
    </div>
    <div id="reservation-details">
        <div>
            <p>Room Type: @Model.RoomType</p>
        </div>
        <div>
            <p>@string.Format(new CultureInfo("uk-UA", false), "Price : {0:C}", price)</p>
        </div>
        <div id="hotel-secvices">
            <p>
                Additional services:
                @if (Model.Parking)
                {
                    parking = "Parking";
                }

                @parking

                @if (Model.Pool)
                {
                    pool = "Pool";
                }

                @pool

                @if (Model.Sauna)
                {
                    sauna = "Sauna";
                }

                @sauna

                @if (Model.TennisCourt)
                {
                    tennisCourt = "TennisCourt";
                }
                @tennisCourt

                @if (Model.Gym)
                {
                    gym = "Gym";
                }
                @gym
                @if (!Model.Parking & !Model.Pool & !Model.Sauna & !Model.TennisCourt & !Model.Gym)
                {
                    absent = "None";
                }
                @absent
            </p>
        </div>
        @if (Model.Status == 0)
        {
            <div id="wrapper-accepting">
                @Html.HiddenFor(m => m.Id)
                @using (Html.BeginForm("DeclineBook", "HotelAdministratorPanel", new { reservationId = Model.Id, hotelId = Model.HotelId }, FormMethod.Post, new { @class = "accepting-form" }))
                {
                    <input type="submit" value="Decline">
                }
                @using (Html.BeginForm("AcceptBook", "HotelAdministratorPanel", new { reservationId = Model.Id, hotelId = Model.HotelId }, FormMethod.Post, new { @class = "accepting-form", @id = "accept" }))
                {
                    <input type="submit" value="Accept">
                }
            </div>
        }
    </div>
</div>